### ISSUE TITLE
Weird behaviour on lower framerate

### ISSUE THREAD

**Issue by KatiKnitt** [cheece/JiggleArmature#4]
Setting the framerate to a lower number will cause jiggle bones to behave differently. In my case, they looked like they got a lot heavier.

**Comment by cheece** [comment]
that's known and unavoidable since the last version used position based dynamics witch depends on frame rate, i'm uploading a new force-based version with new bugs which is not so dependent on frame rate , if you continue using the pbd version just increase the number of sub steps, it should fix the problem

**Comment by KatiKnitt** [comment]
Is there a way to base it on seconds?



Simon Flores <notifications@github.com> schrieb am Do. 1. Juni 2017 um
22:22:
